config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, except: [:index] do
    resources :locations
  end

  resources :sessions, only: [:create]
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  resources :crimes, only: [:index]

end

app/models/crime.rb
class Crime < ActiveRecord::Base

  # validates :latitude, :longitude, :allow_blank => false, :allow_nil => false
  validates_uniqueness_of :date, scope: [:address, :offense]
  geocoded_by :address
  # after_validation :geocode, :if => :address_not_converted?
  # after_validation check for presence of lat/long, then geocode
  after_validation :geocode#, on: :create


  # def address_not_converted?
  #   Crime.all do |crime|
  #     if (crime[:latitude] === nil || crime[:longitude] === nil)
  #       return true
  #     end
  #   end
  # end

end # END of class

# In 'rails c' use Crime.delete_all to empty table
# Or 'rails c --sandbox' if you want to just mess around

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user

  validates :latitude, presence: true
  validates :longitude, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :locations, dependent: :destroy

  before_create :create_remember_token
  before_save :normalize_fields

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end


  def normalize_fields
    self.email.downcase!
  end
end # END of class

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include CrimesHelper
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController

  def index
    @crimes = Crime.all
    render json: @crimes
    # if (crime_data.first[:date] != Crime.all.last[:date])
      # @crimes = crime_data
      #   respond_to do |format|
          # format.html { render :index }
          # format.json { render json: @crimes }
        # end
    # end
  end

  def new
  end

  def create
    @crimes = Crime.new
    if @crimes.save
      render json: @crimes
    else
      render status: 400, nothing: true
    end
  end
end # END of crimes controller

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @user = current_user
    @locations = @user.locations
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @locations }
    end
  end

  def create
    @location = Location.new(location_params)
    @location.user_id = params[:user_id]
    if @location.save
      render json: @location
    else
      render status: 400, nothing: true
    end
  end

private

  def location_params
    params.require(:location).permit(:label, :address, :radius, :latitude, :longitude, :user_id)
  end

end # END of controller 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end # END of class

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation
      )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end

end # END of class

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/crimes_helper.rb
module CrimesHelper

  def crime_data
    response = HTTParty.get('http://data.octo.dc.gov/feeds/crime_incidents/crime_incidents_current.xml')
    data = response.parsed_response
    crimes = data['feed']['entry']
    # if (crimes.last['content']['ReportedCrime']['reportdatetime'] === Crime.all.last[:date])
      crimes.map do |crime|
        Crime.create(
          :date => crime['content']['ReportedCrime']['reportdatetime'], 
          :address => crime['content']['ReportedCrime']['blocksiteaddress'],
          :offense => crime['content']['ReportedCrime']['offense'],
          :method => crime['content']['ReportedCrime']['method'],
          :ward => crime['content']['ReportedCrime']['ward']
        )      
      end
    # end
  end
end # END of crimes module

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in'
      redirect_to signin_url
    end
  end
end # END of module

app/views/common/_signout.html.erb
<% if signed_in? %>

<div class= "user_menu">
  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    Signed in as <%= link_to current_user.email, current_user %>
    <%= f.submit "Sign out", id: 'signout' %>
  <% end %>
    
  <% else %>

    <%= link_to "Sign In", signin_path %> | <%= link_to "Sign up", signup_path %>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloseToHome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Arvo|Oxygen' rel='stylesheet' type='text/css'>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
</head>
<body>

<div class="user_menu">  
  <%= render 'common/signout' %>
</div>
  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
<b>Errors:</b>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="form">
  <%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Submit", id: 'submit' %>
    <%= link_to "Cancel", root_path %>
</div>
  <% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.email %></h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/new.html.erb
<h1>Create an Account</h1>
<%= render "user_form" %>

app/views/users/show.html.erb
<%= link_to "Home Page", root_path, class: "user_menu" %>
<%= link_to "Update Account", edit_user_path(@user), class: "user_menu" %>

<h1>Crimes in your area</h1>

<div id="map-canvas" class="map_show"></div>

<div id="locationField" class="locationField">
  <input id="autocomplete" placeholder="Enter your address" onFocus="mapPage.geolocate()" type="text">
</div>

app/views/welcome/index.html.erb
<h1>Close to Home</h1>

<div class="my_locations">
  <% if current_user %>
    <%= link_to "My Locations", current_user %>
  <% else %>
    <%= '' %>
  <% end %>

</div>

<div id="map-canvas" class="map_index"></div>